"""
Turns raw log lines into numeric feature vectors the model can learn from.

Design choice: rather than embedding raw text (which needs a pretrained
language model), we hand-engineer features that any SRE would recognize as
crash-loop / incident signals. This keeps the whole detector dependency-light,
fast to train, fully offline, and easy to explain in a report:

  - log_rate              lines seen per second in the window
  - error_ratio            fraction of lines at ERROR level
  - warn_ratio             fraction of lines at WARN level
  - restart_signal         hits for "restart", "back-off", "terminated", "starting container"
  - oom_signal             hits for "oomkilled", "memory usage"
  - conn_signal            hits for "connection refused", "timeout", "deadline exceeded"
  - panic_signal           hits for "panic", "exception", "traceback", "unhandled"
  - distinct_error_types   fraction of unique error message templates in window
  - avg_latency            mean latency (ms) parsed out of request log lines
  - latency_spike          max latency in window relative to a fixed baseline
  - novel_template_ratio   fraction of lines whose Drain3 template was never
                           seen in the "known-good" training corpus (optional —
                           only populated when a template_miner is supplied;
                           see detector/template_miner.py)

parse_line() supports two log formats to handle real-world heterogeneous streams:
  1. Structured text: "<ts> <LEVEL> [<pod>] <msg>"  (generated by this project)
  2. JSON: {"ts":..., "level":..., "pod":..., "message":...}  (common in prod)

Lines that match neither format are silently counted as unparsable.  Callers
can query how many lines were dropped via extract_windows()'s return value or
the logged warnings.
"""

import json
import logging
import re
from collections import defaultdict, deque

logger = logging.getLogger("features")

LOG_RE = re.compile(
    r"^(?P<ts>\S+)\s+(?P<level>\w+)\s+\[(?P<pod>[^\]]+)\]\s+(?P<msg>.*)$"
)
LATENCY_RE = re.compile(r"(\d+)ms")

RESTART_KEYWORDS = ["back-off", "restarting", "terminated", "starting container"]
OOM_KEYWORDS = ["oomkilled", "memory usage"]
CONN_KEYWORDS = ["connection refused", "timeout", "deadline exceeded", "503"]
PANIC_KEYWORDS = ["panic", "exception", "traceback", "unhandled", "nil pointer"]

FEATURE_NAMES = [
    "log_rate",
    "error_ratio",
    "warn_ratio",
    "restart_signal",
    "oom_signal",
    "conn_signal",
    "panic_signal",
    "distinct_error_types",
    "avg_latency",
    "latency_spike",
    "novel_template_ratio",
]

# JSON field name aliases — different frameworks use different key names.
_JSON_LEVEL_KEYS = ("level", "severity", "lvl")
_JSON_MSG_KEYS = ("message", "msg", "text", "body")
_JSON_POD_KEYS = ("pod", "pod_name", "kubernetes.pod_name")
_JSON_TS_KEYS = ("ts", "timestamp", "time", "@timestamp")


def parse_line(line):
    """
    Parse a single log line into a dict with keys: ts, level, pod, msg.
    Returns None if the line cannot be parsed in any supported format.

    Supported formats:
      1. "<ts> <LEVEL> [<pod>] <msg>"  — structured text (project-native)
      2. JSON object with recognisable level/pod/message keys
    """
    line = line.strip()
    if not line:
        return None

    # --- Format 1: structured text ---
    m = LOG_RE.match(line)
    if m:
        return m.groupdict()

    # --- Format 2: JSON ---
    if line.startswith("{"):
        try:
            obj = json.loads(line)
        except (json.JSONDecodeError, ValueError):
            return None

        def _first(keys):
            for k in keys:
                if k in obj:
                    return str(obj[k])
            return None

        ts = _first(_JSON_TS_KEYS) or "unknown"
        level = _first(_JSON_LEVEL_KEYS) or "INFO"
        pod = _first(_JSON_POD_KEYS) or "unknown"
        msg = _first(_JSON_MSG_KEYS) or ""
        return {"ts": ts, "level": level, "pod": pod, "msg": msg}

    return None


def _keyword_hits(msg_lower, keywords):
    return sum(1 for k in keywords if k in msg_lower)


class PodWindow:
    """Rolling window of parsed log entries for a single pod."""

    def __init__(self, size=20):
        self.size = size
        self.entries = deque(maxlen=size)

    def add(self, entry):
        self.entries.append(entry)

    def is_full(self):
        return len(self.entries) == self.size

    def to_features(self):
        entries = list(self.entries)
        n = len(entries)
        if n == 0:
            return [0.0] * len(FEATURE_NAMES)

        error_count = 0
        warn_count = 0
        restart_hits = 0
        oom_hits = 0
        conn_hits = 0
        panic_hits = 0
        error_messages = set()
        latencies = []

        t0 = entries[0]["ts"]
        t1 = entries[-1]["ts"]

        for e in entries:
            level = e["level"].upper()
            msg_lower = e["msg"].lower()

            if level == "ERROR":
                error_count += 1
                error_messages.add(msg_lower[:40])
            elif level == "WARN" or level == "WARNING":
                warn_count += 1

            restart_hits += _keyword_hits(msg_lower, RESTART_KEYWORDS)
            oom_hits += _keyword_hits(msg_lower, OOM_KEYWORDS)
            conn_hits += _keyword_hits(msg_lower, CONN_KEYWORDS)
            panic_hits += _keyword_hits(msg_lower, PANIC_KEYWORDS)

            lat = LATENCY_RE.search(msg_lower)
            if lat:
                latencies.append(int(lat.group(1)))

        try:
            from datetime import datetime

            dt0 = datetime.fromisoformat(t0.replace("Z", "+00:00"))
            dt1 = datetime.fromisoformat(t1.replace("Z", "+00:00"))
            duration = max((dt1 - dt0).total_seconds(), 0.01)
        except Exception:
            duration = 1.0

        log_rate = n / duration
        error_ratio = error_count / n
        warn_ratio = warn_count / n
        distinct_error_types = (len(error_messages) / error_count) if error_count else 0.0
        avg_latency = sum(latencies) / len(latencies) if latencies else 0.0
        latency_spike = max(latencies) if latencies else 0.0

        # Template-mining feature (see detector/template_miner.py). Stays
        # 0.0 if extract_windows() wasn't given a template_miner, so this
        # module still works standalone / in tests without Drain3.
        novel_count = sum(1 for e in entries if e.get("is_novel_template"))
        novel_template_ratio = novel_count / n

        return [
            log_rate,
            error_ratio,
            warn_ratio,
            restart_hits / n,
            oom_hits / n,
            conn_hits / n,
            panic_hits / n,
            distinct_error_types,
            avg_latency,
            latency_spike,
            novel_template_ratio,
        ]


def extract_windows(lines, window_size=20, stride=5, template_miner=None):
    """
    Streams through log lines, grouping per-pod, and yields
    (pod, end_line_index, feature_vector) for every full window.
    Stride controls how often we emit a window (5 = emit every 5 new lines).

    If template_miner is provided (a detector.template_miner.TemplateMinerWrapper),
    each parsed line's message is also run through Drain3 to attach
    cluster_id / is_novel_template info used by the two template-based
    features in PodWindow.to_features(). Omit it to run with keyword-based
    features only (e.g. for quick tests without the Drain3 dependency).

    Returns a list of window dicts. Also logs a warning if a significant
    fraction of lines cannot be parsed, so silent data loss is visible.
    """
    pod_windows = defaultdict(lambda: PodWindow(size=window_size))
    pod_counters = defaultdict(int)
    results = []

    total = 0
    unparsed = 0

    for i, raw in enumerate(lines):
        total += 1
        parsed = parse_line(raw)
        if not parsed:
            unparsed += 1
            continue

        if template_miner is not None:
            cluster_id, is_novel = template_miner.process(parsed["msg"])
            parsed["cluster_id"] = cluster_id
            parsed["is_novel_template"] = is_novel

        pod = parsed["pod"]
        pod_windows[pod].add(parsed)
        pod_counters[pod] += 1

        if pod_windows[pod].is_full() and pod_counters[pod] % stride == 0:
            feats = pod_windows[pod].to_features()
            results.append({"pod": pod, "end_line": i, "features": feats})

    if total > 0 and unparsed > 0:
        pct = unparsed / total * 100
        # Only warn if more than 5% of lines are unparsed — a small number of
        # unparsable lines (metadata, blank lines) is expected.
        if pct > 5.0:
            logger.warning(
                "extract_windows: %d/%d lines (%.1f%%) could not be parsed. "
                "Check log format — both '<ts> LEVEL [pod] msg' and JSON are supported.",
                unparsed, total, pct,
            )

    return results
